twitter:
	consumer_key: "zB93XCuq08r3xJqJ1T8vw"
	consumer_secret: "FZ7HuRBDAzLidL91vQpdyr7a1cQZ55PNIEMGJFBloo"
	oauth_token: "20256024-NRZOI4e1lFZS6XJdvFeeoNDmavEv8lL9dTEZ0qTv0"
	oauth_token_secret: "ic4oTyYY6hv5ZoxgU5zn10PzMm7XIvsWNuuEbFiTCbw"